### ISSUE TITLE
can't be installed

### ISSUE THREAD

**Issue by 12-zhx** [danpovey/lilcom#44]
why I cann't install it.

**Comment by csukuangfj** [comment]
Please give more information.
E.g., 

- which operating system are you using
- what are the error logs

**Comment by 12-zhx** [comment]
(Pytorch_lightning) F:\Project\mfa_conformer-master>pip install lilcom
Collecting lilcom
  Using cached lilcom-1.3.tar.gz (44 kB)
Requirement already satisfied: numpy<1.23.0 in d:\anaconda3\envs\pytorch_lightning\lib\site-packages (from lilcom) (1.22.4)
Building wheels for collected packages: lilcom
  Building wheel for lilcom (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'D:\Anaconda3\envs\Pytorch_lightning\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\28705\\AppData\\Local\\Temp\\pip-install-h3m1o_mk\\lilcom_e250b98bc22e40868793e23d65252476\\setup.py'"'"'; __file__='"'"'C:\\Users\\28705\\AppData\\Local\\Temp\\pip-install-h3m1o_mk\\lilcom_e250b98bc22e40868793e23d65252476\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\28705\AppData\Local\Temp\pip-wheel-eq9q2i9d'
       cwd: C:\Users\28705\AppData\Local\Temp\pip-install-h3m1o_mk\lilcom_e250b98bc22e40868793e23d65252476\
  Complete output (73 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\lilcom
  copying lilcom\lilcom_interface.py -> build\lib.win-amd64-3.8\lilcom
  copying lilcom\__init__.py -> build\lib.win-amd64-3.8\lilcom
  running build_ext
  -- Building for: NMake Makefiles
  CMake Error at CMakeLists.txt:2 (project):
    Running

     'nmake' '-?'

    failed with:

     绯荤粺鎵句笉鍒版寚瀹氱殑鏂囦欢銆\x82


  CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
  CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
  -- Configuring incomplete, errors occurred!
  See also "C:/Users/28705/AppData/Local/Temp/pip-install-h3m1o_mk/lilcom_e250b98bc22e40868793e23d65252476/build/temp.win-amd64-3.8/Release/CMakeFiles/CMakeOutput.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\28705\AppData\Local\Temp\pip-install-h3m1o_mk\lilcom_e250b98bc22e40868793e23d65252476\setup.py", line 52, in <module>
      setuptools.setup(
    File "D:\Anaconda3\envs\Pytorch_lightning\lib\site-packages\setuptools\__init__.py", line 87, in setup
      return distutils.core.setup(**attrs)
    File "D:\Anaconda3\envs\Pytorch_lightning\lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
      return run_commands(dist)
    File "D:\Anaconda3\envs\Pytorch_lightning\lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
      dist.run_commands()
    File "D:\Anaconda3\envs\Pytorch_lightning\lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
      self.run_command(cmd)
    File "D:\Anaconda3\envs\Pytorch_lightning\lib\site-packages\setuptools\dist.py", line 1214, in run_command
      super().run_command(command)
    File "D:\Anaconda3\envs\Pytorch_lightning\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "D:\Anaconda3\envs\Pytorch_lightning\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "D:\Anaconda3\envs\Pytorch_lightning\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "D:\Anaconda3\envs\Pytorch_lightning\lib\site-packages\setuptools\dist.py", line 1214, in run_command
      super().run_command(command)
    File "D:\Anaconda3\envs\Pytorch_lightning\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "D:\Anaconda3\envs\Pytorch_lightning\lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "D:\Anaconda3\envs\Pytorch_lightning\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "D:\Anaconda3\envs\Pytorch_lightning\lib\site-packages\setuptools\dist.py", line 1214, in run_command
      super().run_command(command)
    File "D:\Anaconda3\envs\Pytorch_lightning\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "D:\Anaconda3\envs\Pytorch_lightning\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
      _build_ext.run(self)
    File "D:\Anaconda3\envs\Pytorch_lightning\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 339, in run
      self.build_extensions()
    File "D:\Anaconda3\envs\Pytorch_lightning\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "D:\Anaconda3\envs\Pytorch_lightning\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 473, in _build_extensions_serial
      self.build_extension(ext)
    File "C:\Users\28705\AppData\Local\Temp\pip-install-h3m1o_mk\lilcom_e250b98bc22e40868793e23d65252476\cmake\cmake_extension.py", line 77, in build_extension
      raise Exception("Failed to build lilcom_extension")
  Exception: Failed to build lilcom_extension
  Setting PYTHON_EXECUTABLE to D:\Anaconda3\envs\Pytorch_lightning\python.exe
  build command is:

                  cmake -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=D:\Anaconda3\envs\Pytorch_lightning\python.exe -B build\temp.win-amd64-3.8\Release -S C:\Users\28705\AppData\Local\Temp\pip-install-h3m1o_mk\lilcom_e250b98bc22e40868793e23d65252476
                  cmake --build build\temp.win-amd64-3.8\Release --target lilcom_extension --config Release -- -m

  ----------------------------------------
  ERROR: Failed building wheel for lilcom
  Running setup.py clean for lilcom
Failed to build lilcom
Installing collected packages: lilcom
    Running setup.py install for lilcom ... error
    ERROR: Command errored out with exit status 1:
     command: 'D:\Anaconda3\envs\Pytorch_lightning\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\28705\\AppData\\Local\\Temp\\pip-install-h3m1o_mk\\lilcom_e250b98bc22
e40868793e23d65252476\\setup.py'"'"'; __file__='"'"'C:\\Users\\28705\\AppData\\Local\\Temp\\pip-install-h3m1o_mk\\lilcom_e250b98bc22e40868793e23d65252476\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open
)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'
"'))' install --record 'C:\Users\28705\AppData\Local\Temp\pip-record-kq8j2gj2\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\Anaconda3\envs\Pytorch_lightning\Include\lilcom'
         cwd: C:\Users\28705\AppData\Local\Temp\pip-install-h3m1o_mk\lilcom_e250b98bc22e40868793e23d65252476\
    Complete output (77 lines):
    running install
    D:\Anaconda3\envs\Pytorch_lightning\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.       
      warnings.warn(
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\lilcom
    copying lilcom\lilcom_interface.py -> build\lib.win-amd64-3.8\lilcom
    copying lilcom\__init__.py -> build\lib.win-amd64-3.8\lilcom
    running build_ext
    -- Building for: NMake Makefiles
    CMake Error at CMakeLists.txt:2 (project):
      Running

       'nmake' '-?'

      failed with:

       绯荤粺鎵句笉鍒版寚瀹氱殑鏂囦欢銆\x82


    CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
    CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
    -- Configuring incomplete, errors occurred!
    See also "C:/Users/28705/AppData/Local/Temp/pip-install-h3m1o_mk/lilcom_e250b98bc22e40868793e23d65252476/build/temp.win-amd64-3.8/Release/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\28705\AppData\Local\Temp\pip-install-h3m1o_mk\lilcom_e250b98bc22e40868793e23d65252476\setup.py", line 52, in <module>
        setuptools.setup(
      File "D:\Anaconda3\envs\Pytorch_lightning\lib\site-packages\setuptools\__init__.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "D:\Anaconda3\envs\Pytorch_lightning\lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
        return run_commands(dist)
      File "D:\Anaconda3\envs\Pytorch_lightning\lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
        dist.run_commands()
      File "D:\Anaconda3\envs\Pytorch_lightning\lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
        self.run_command(cmd)
      File "D:\Anaconda3\envs\Pytorch_lightning\lib\site-packages\setuptools\dist.py", line 1214, in run_command
        super().run_command(command)
      File "D:\Anaconda3\envs\Pytorch_lightning\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
        cmd_obj.run()
      File "D:\Anaconda3\envs\Pytorch_lightning\lib\site-packages\setuptools\command\install.py", line 68, in run
        return orig.install.run(self)
      File "D:\Anaconda3\envs\Pytorch_lightning\lib\site-packages\setuptools\_distutils\command\install.py", line 664, in run
        self.run_command('build')
      File "D:\Anaconda3\envs\Pytorch_lightning\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "D:\Anaconda3\envs\Pytorch_lightning\lib\site-packages\setuptools\dist.py", line 1214, in run_command
        super().run_command(command)
      File "D:\Anaconda3\envs\Pytorch_lightning\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
        cmd_obj.run()
      File "D:\Anaconda3\envs\Pytorch_lightning\lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "D:\Anaconda3\envs\Pytorch_lightning\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "D:\Anaconda3\envs\Pytorch_lightning\lib\site-packages\setuptools\dist.py", line 1214, in run_command
        super().run_command(command)
      File "D:\Anaconda3\envs\Pytorch_lightning\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
        cmd_obj.run()
      File "D:\Anaconda3\envs\Pytorch_lightning\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
        _build_ext.run(self)
      File "D:\Anaconda3\envs\Pytorch_lightning\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 339, in run
        self.build_extensions()
      File "D:\Anaconda3\envs\Pytorch_lightning\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "D:\Anaconda3\envs\Pytorch_lightning\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "C:\Users\28705\AppData\Local\Temp\pip-install-h3m1o_mk\lilcom_e250b98bc22e40868793e23d65252476\cmake\cmake_extension.py", line 77, in build_extension
        raise Exception("Failed to build lilcom_extension")
    Exception: Failed to build lilcom_extension
    Setting PYTHON_EXECUTABLE to D:\Anaconda3\envs\Pytorch_lightning\python.exe
    build command is:

                    cmake -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=D:\Anaconda3\envs\Pytorch_lightning\python.exe -B build\temp.win-amd64-3.8\Release -S C:\Users\28705\AppData\Local\Temp\pip-install-h3m1o_mk\lilcom_e250b98bc22e40868793e23d65252476
                    cmake --build build\temp.win-amd64-3.8\Release --target lilcom_extension --config Release -- -m

    ----------------------------------------
ERROR: Command errored out with exit status 1: 'D:\Anaconda3\envs\Pytorch_lightning\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\28705\\AppData\\Local\\Temp\\pip-ins
tall-h3m1o_mk\\lilcom_e250b98bc22e40868793e23d65252476\\setup.py'"'"'; __file__='"'"'C:\\Users\\28705\\AppData\\Local\\Temp\\pip-install-h3m1o_mk\\lilcom_e250b98bc22e40868793e23d65252476\\setup.py'"'"';f = getat
tr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(com
pile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\28705\AppData\Local\Temp\pip-record-kq8j2gj2\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\Anaconda3\envs\Pytorch_lightning\Include\lilcom' Check the logs for full command output.

**Comment by 12-zhx** [comment]
I use window11

**Comment by 12-zhx** [comment]
And I have tried offline installation,  it doesn't work ,either

**Comment by csukuangfj** [comment]
Please wait a moment, I am supporting 
```
conda install -c lilcom lilcom
```
