### ISSUE TITLE
Error when installing lhotse

### ISSUE THREAD

**Issue by treya-lin** [danpovey/lilcom#50]
Hi, I am trying to install lhoste in docker, and I was unable to install lilcom. I tried to install it separately and I tried 1.3, 1.4 and 1.5 and none worked. Would you mind take a look at this error log. Thanks!

```
Collecting lilcom>=1.1.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/00/93/13666e5015803fc10ee755838f7d8a8b0b0643377d3a82a7e613afe1a819/lilcom-1.5.tar.gz (45 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.8/45.8 kB 837.0 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-jbrwvxxq/lilcom_d57f9e34639a480ba981ac5731a289d8/setup.py", line 73, in <module>
          "License :: OSI Approved :: MIT License",
        File "/opt/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/opt/anaconda3/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/opt/anaconda3/lib/python3.7/site-packages/setuptools/dist.py", line 479, in __init__
          for k, v in attrs.items()
        File "/opt/anaconda3/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
          self.finalize_options()
        File "/opt/anaconda3/lib/python3.7/site-packages/setuptools/dist.py", line 898, in finalize_options
          for ep in sorted(loaded, key=by_order):
        File "/opt/anaconda3/lib/python3.7/site-packages/setuptools/dist.py", line 897, in <lambda>
          loaded = map(lambda e: e.load(), filtered)
        File "/opt/anaconda3/lib/python3.7/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 196, in load
          return functools.reduce(getattr, attrs, module)
      AttributeError: type object 'Distribution' has no attribute '_finalize_feature_opts'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by csukuangfj** [comment]
The quickest fix is to run
```
conda install -c lilcom lilcom
```
and then install lhotse.

**Comment by csukuangfj** [comment]
The reason for your error can be found at
https://github.com/pypa/setuptools/issues/2029

It has something to do with your installed `setuptools`.

**Comment by treya-lin** [comment]
> 

Hi I ran this command, and it failed at "verifying transaction" stage. 

```
Proceed ([y]/n)? y


Downloading and Extracting Packages
certifi-2022.9.24    | 154 KB    | ################################################################################################################################################################################################################## | 100% 
markupsafe-2.0.1     | 21 KB     | ################################################################################################################################################################################################################## | 100% 
anaconda-custom      | 3 KB      | ################################################################################################################################################################################################################## | 100% 
ca-certificates-2022 | 124 KB    | ################################################################################################################################################################################################################## | 100% 
charset-normalizer-2 | 35 KB     | ################################################################################################################################################################################################################## | 100% 
itsdangerous-2.0.1   | 18 KB     | ################################################################################################################################################################################################################## | 100% 
tqdm-4.64.1          | 126 KB    | ################################################################################################################################################################################################################## | 100% 
flask-1.1.2          | 70 KB     | ################################################################################################################################################################################################################## | 100% 
werkzeug-2.0.3       | 221 KB    | ################################################################################################################################################################################################################## | 100% 
dataclasses-0.8      | 8 KB      | ################################################################################################################################################################################################################## | 100% 
_anaconda_depends-20 | 6 KB      | ################################################################################################################################################################################################################## | 100% 
six-1.16.0           | 18 KB     | ################################################################################################################################################################################################################## | 100% 
scipy-1.6.2          | 15.4 MB   | ################################################################################################################################################################################################################## | 100% 
pip-22.2.2           | 2.3 MB    | ################################################################################################################################################################################################################## | 100% 
requests-2.28.1      | 92 KB     | ################################################################################################################################################################################################################## | 100% 
openssl-1.1.1s       | 3.6 MB    | ################################################################################################################################################################################################################## | 100% 
click-8.0.4          | 152 KB    | ################################################################################################################################################################################################################## | 100% 
lilcom-1.4           | 63 KB     | ################################################################################################################################################################################################################## | 100% 
jinja2-2.11.3        | 101 KB    | ################################################################################################################################################################################################################## | 100% 
Preparing transaction: done
Verifying transaction: failed

RemoveError: 'requests' is a dependency of conda and cannot be removed from
conda's operating environment.

```

**Comment by treya-lin** [comment]
> The quickest fix is to run
> 
> ```
> conda install -c lilcom lilcom
> ```
> 
> and then install lhotse.

Hi  @csukuangfj I ran this command, and it failed at "verifying transaction" stage.
```
Proceed ([y]/n)? y


Downloading and Extracting Packages
certifi-2022.9.24    | 154 KB    | ################################################################################################################################################################################################################## | 100% 
markupsafe-2.0.1     | 21 KB     | ################################################################################################################################################################################################################## | 100% 
anaconda-custom      | 3 KB      | ################################################################################################################################################################################################################## | 100% 
ca-certificates-2022 | 124 KB    | ################################################################################################################################################################################################################## | 100% 
charset-normalizer-2 | 35 KB     | ################################################################################################################################################################################################################## | 100% 
itsdangerous-2.0.1   | 18 KB     | ################################################################################################################################################################################################################## | 100% 
tqdm-4.64.1          | 126 KB    | ################################################################################################################################################################################################################## | 100% 
flask-1.1.2          | 70 KB     | ################################################################################################################################################################################################################## | 100% 
werkzeug-2.0.3       | 221 KB    | ################################################################################################################################################################################################################## | 100% 
dataclasses-0.8      | 8 KB      | ################################################################################################################################################################################################################## | 100% 
_anaconda_depends-20 | 6 KB      | ################################################################################################################################################################################################################## | 100% 
six-1.16.0           | 18 KB     | ################################################################################################################################################################################################################## | 100% 
scipy-1.6.2          | 15.4 MB   | ################################################################################################################################################################################################################## | 100% 
pip-22.2.2           | 2.3 MB    | ################################################################################################################################################################################################################## | 100% 
requests-2.28.1      | 92 KB     | ################################################################################################################################################################################################################## | 100% 
openssl-1.1.1s       | 3.6 MB    | ################################################################################################################################################################################################################## | 100% 
click-8.0.4          | 152 KB    | ################################################################################################################################################################################################################## | 100% 
lilcom-1.4           | 63 KB     | ################################################################################################################################################################################################################## | 100% 
jinja2-2.11.3        | 101 KB    | ################################################################################################################################################################################################################## | 100% 
Preparing transaction: done
Verifying transaction: failed

RemoveError: 'requests' is a dependency of conda and cannot be removed from
conda's operating environment.
```

**Comment by csukuangfj** [comment]
The error is
```
RemoveError: 'requests' is a dependency of conda and cannot be removed from
conda's operating environment.
```

You can either use
```
conda remove requests
conda install -c lilcom lilcom
```
or create a new environment, e.g, with name `k2`:

```bash
conda create -n k2
conda activate k2
conda install -c lilcom lilcom
```
